apiVersion: v1
kind: Service
metadata:
  name: spark-service
  labels:
    app: CAP
    role: leader
    tier: backend
spec:
  ports:
  - port: 7077
    targetPort: 7077
  selector:
    app: CAP
    role: leader
    tier: backend